#!/bin/bash
# __SP_application: kickstart
# __SP_version: 1
# __SP_runtime: bash
# __SP_api_version: 2
#

shellpack_home=`dirname ${SHELLPACK_KICKSTART}`
shellpack_home=${shellpack_home%%/lib}

shellpack_user_home="${HOME}/shellpack"
shellpack_home=${SHELLPACK_HOME:-${shellpack_home}}
shellpack_lib="${shellpack_home}/lib"
shellpack_cfg="${shellpack_home}/cfg"

shellpack_api_version="2"
shellpack_lib_preid="__SP_"

# set defaults ------------------------------------------------------------------
shellpack_hosts="${shellpack_user_home}/hosts"
shellpack_queues="${shellpack_user_home}/queues"
shellpack_lock="${shellpack_user_home}/lock"
shellpack_keys="${shellpack_user_home}/keys"

shellpack_libext="lib.sh"
shellpack_lckext="lck"
shellpack_sshkeyext="sshkey"

# common functions --------------------------------------------------------------
shellpack_functions="${shellpack_lib}/functions"
if ! test -r ${shellpack_functions} ; then
  echo "functions error"
  exit 10
fi
. ${shellpack_functions}

# create directories ------------------------------------------------------------
create_directory "${shellpack_lock}"
create_directory "${shellpack_keys}"
